### YamlMime:ManagedReference
items:
- uid: System.Activities.Statements.Catch
  id: Catch
  children:
  - System.Activities.Statements.Catch.ExceptionType
  langs:
  - csharp
  name: Catch
  nameWithType: Catch
  fullName: System.Activities.Statements.Catch
  type: Class
  summary: "包含要将在相应引发异常后执行的操作<xref uid=&quot;langword_csharp_Try&quot; name=&quot;Try&quot; href=&quot;&quot;></xref>块<xref:System.Activities.Statements.TryCatchFinally>活动。</xref:System.Activities.Statements.TryCatchFinally>"
  remarks: "一旦放置在设计器中，Catch 活动不能在设计器中重新排序。  要重新排序的 Catch 活动的集合，删除并重新将其添加顺序正确，或者使用工作流 xaml （代码） 视图。"
  syntax:
    content: public abstract class Catch
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Activities.Statements.Catch.ExceptionType
  id: ExceptionType
  parent: System.Activities.Statements.Catch
  langs:
  - csharp
  name: ExceptionType
  nameWithType: Catch.ExceptionType
  fullName: System.Activities.Statements.Catch.ExceptionType
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Statements
  summary: "异常的类型， <xref href=&quot;System.Activities.Statements.Catch&quot;> </xref>块正在处理。"
  syntax:
    content: public abstract Type ExceptionType { get; }
    return:
      type: System.Type
      description: "异常类型。"
  overload: System.Activities.Statements.Catch.ExceptionType*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Activities.Statements.Catch.ExceptionType
  parent: System.Activities.Statements.Catch
  isExternal: false
  name: ExceptionType
  nameWithType: Catch.ExceptionType
  fullName: System.Activities.Statements.Catch.ExceptionType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Activities.Statements.Catch.ExceptionType*
  parent: System.Activities.Statements.Catch
  isExternal: false
  name: ExceptionType
  nameWithType: Catch.ExceptionType
